on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-18.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install Yarn dependencies in next-app
        run: sleep 2m
