on:
  workflow_dispatch:
    inputs:
      # See https://github.com/actions/runner/issues/475#issuecomment-742271143
      WEBHOOK_TOKEN:
        description: "Access token"
        required: true

jobs:
  e2e:
    runs-on: ubuntu-18.04
    env:
      APP_URL: https://bcgov.github.io/sso-terraform-dev/
    steps:
      - uses: actions/checkout@v2

      # NPM PACKAGES
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies in next-app
        run: yarn
        # working-directory: ./app

      # NodeJS APP & Cypress
      - name: Run local app & e2e tests
        env:
          CYPRESS_APP_URL: ${{ env.APP_URL }}
          CYPRESS_TOKEN: ${{ github.event.inputs.tokens }}
        run: |
          yarn cypress run
        # working-directory: ./app
