on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-18.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: sleep
        run: |
          until exit 1;
          do echo retrying in 10 seconds...
          sleep 10
          done