name: Request

on:
  workflow_dispatch:

jobs:
  iss:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://cttuyb3bsf.execute-api.ca-central-1.amazonaws.com/test/actions'
          method: 'PUT'
          data: '{"prNumber: 10", "success": false, "id": 1}'
          customHeaders: '{"Authorization": "secret"}'