name: Request

on: pull_request

jobs:
  iss:
    runs-on: ubuntu-18.04
    steps:
      - name: control
        run: echo hi
      - name: label test
        if: github.event.label.name == 'bug'
        run: echo holy guacomole it worked