name: Request

on: [pull_request, push]

jobs:
  iss:
    runs-on: ubuntu-18.04
    steps:
      - name: control
        run: echo "${{github.event.label}}"
      - name: label test
        if: github.event.label.name == 'bug'
        run: echo holy guacomole it worked

      - name: Update Apply Status
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://example.com:81'
          method: 'GET'
          timeout: '60000'
