name: Request

on:
  workflow_dispatch:

jobs:
  iss:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/test.js')
            script( {github, context} )